services:
  mongodb1:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db

  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    ports:
      - 8000:8080
    environment:
      MONGODB_URL: "mongodb://mongodb1"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  mongodb_data_container: